"""About Author added

Revision ID: 779b11aeebe7
Revises: c7f8a7a05fbf
Create Date: 2024-07-17 23:06:35.440912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779b11aeebe7'
down_revision = 'c7f8a7a05fbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_author', sa.Text(length=400), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('about_author')

    # ### end Alembic commands ###
